=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/dataset.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:dflt="tablehockey">
	<xsd:import namespace="tablehockey" schemaLocation="tablehockey.xsd" />
	<xsd:element name="dataset">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element name="final_standing" type="dflt:final_standing__type" />
				<xsd:element name="game" type="dflt:game__type" />
				<xsd:element name="group_participant" type="dflt:group_participant__type" />
				<xsd:element name="groups" type="dflt:groups__type" />
				<xsd:element name="ithf_tournament" type="dflt:ithf_tournament__type" />
				<xsd:element name="matchs" type="dflt:matchs__type" />
				<xsd:element name="participant" type="dflt:participant__type" />
				<xsd:element name="play_off_game" type="dflt:play_off_game__type" />
				<xsd:element name="player" type="dflt:player__type" />
				<xsd:element name="playing_format" type="dflt:playing_format__type" />
				<xsd:element name="rating" type="dflt:rating__type" />
				<xsd:element name="rating_points" type="dflt:rating_points__type" />
				<xsd:element name="stage" type="dflt:stage__type" />
				<xsd:element name="tournament" type="dflt:tournament__type" />
				<xsd:element name="tournament_admin" type="dflt:tournament_admin__type" />
				<xsd:element name="tournament_rating" type="dflt:tournament_rating__type" />
				<xsd:element name="user" type="dflt:user__type" />
				<xsd:any namespace="tablehockey" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/participant/group/updateGroupParticipantTest-verify.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../dataset.xsd">

    <tournament id="1" name="@any" status="RO" playing_format_id="@null" country="@any" city="@any" address="@any"
        logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp" visible="true" />

    <stage copy_result_stage_id="@null" id="1" name="@any" number_of_hockey="@any" sequence="@any" status="NS"
        tournament_id="1" type="RR" win_points="@any" />

    <groups id="1" name="@any" stage_id="1" />

    <player id="1" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="2" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />

    <participant id="@any" player_id="1" tournament_id="1" />

    <group_participant id="1" group_id="1" points="2" rank="2" score="2:2" secondary_rank="2" participant_id="1"/>
 
</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/finalStanding/updateFinalStandingTest-verify.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../dataset.xsd">

    <tournament id="1" name="@auto" status="RO" playing_format_id="@null" country="@auto" city="@auto"
        address="@auto" logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp"
        visible="true" />

    <player id="1" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />
    <player id="2" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />

    <user player_id="1" email="@auto" login="@auto" password="@auto" phone="@auto" role="USER" validity="1" />

    <participant id="1" player_id="1" tournament_id="1" />
    <participant id="2" player_id="2" tournament_id="1" />

    <final_standing id="1" final_rank="11" participant_id="2" />

</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/playOffGame/PlayOffGameIT.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../dataset.xsd">

    <tournament id="1" name="@auto" status="RO" playing_format_id="@null" country="@auto" city="@auto"
        address="@auto" logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp"
        visible="true" />

    <stage copy_result_stage_id="@null" id="1" name="@auto" number_of_hockey="@auto" sequence="@auto" status="NS"
        tournament_id="1" type="RR" win_points="@auto" />

    <player id="1" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />
    <player id="2" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />
    <player id="3" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />
    <player id="4" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />
    <player id="5" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />

    <groups id="1" name="@auto" stage_id="1" />

    <participant id="1" player_id="1" tournament_id="1" />
    <participant id="2" player_id="2" tournament_id="1" />
    <participant id="3" player_id="3" tournament_id="1" />
    <participant id="4" player_id="4" tournament_id="1" />
    <participant id="5" player_id="5" tournament_id="1" />

    <group_participant id="1" group_id="1" participant_id="1" points="0" rank="@null" score="0:0"
        secondary_rank="@null" />
    <group_participant id="2" group_id="1" participant_id="2" points="0" rank="@null" score="0:0"
        secondary_rank="@null" />
    <group_participant id="3" group_id="1" participant_id="3" points="0" rank="@null" score="0:0"
        secondary_rank="@null" />
    <group_participant id="4" group_id="1" participant_id="4" points="0" rank="@null" score="0:0"
        secondary_rank="@null" />
    <group_participant id="5" group_id="1" participant_id="5" points="0" rank="@null" score="0:0"
        secondary_rank="@null" />

    <play_off_game id="1" home_participant_id="1" away_participant_id="2" position="1" result="1:0"
        stage_id="1" status="WIN" />

</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/match/getMatchTest-verify.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../dataset.xsd">
 
    <tournament id="1" name="@any" status="RO" playing_format_id="@null" country="@any" city="@any" address="@any"
        logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp" visible="true" />

    <stage copy_result_stage_id="@null" id="1" name="@any" number_of_hockey="@any" sequence="@any" status="NS"
        tournament_id="1" type="RR" win_points="@any" />

    <player id="1" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="2" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />

    <groups id="1" name="@any" stage_id="1" />
    <groups id="2" name="@any" stage_id="1" />

    <participant id="1" player_id="1" tournament_id="1" />
    <participant id="2" player_id="2" tournament_id="1" />

    <group_participant id="1" group_id="1" participant_id="1" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />
    <group_participant id="2" group_id="1" participant_id="2" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />

    <game id="1" home_group_participant_id="1" away_group_participant_id="2" result="@null" status="@null" />
    <game id="2" home_group_participant_id="2" away_group_participant_id="1" result="@null" status="@null" />

    <matchs id="1" home_player_id="1" away_player_id="2" game_id="1" group_id="1" round="1" hockey="1" />

</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/clear-all.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../dataset.xsd">

    <final_standing />
    <game />
    <group_participant />
    <groups />
    <ithf_tournament />
    <play_off_game />
    <player />
    <playing_format />
    <rating />
    <rating_points />
    <stage />
    <tournament />
    <tournament_admin />
    <participant />
    <tournament_rating />
    <user />

</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/registration/registerParticipant-verify.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../dataset.xsd">

    <tournament id="1" name="@any" status="RO" playing_format_id="@null" country="@any" city="@any" address="@any"
        logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp" visible="true" />

    <stage copy_result_stage_id="@null" id="1" name="@any" number_of_hockey="@any" sequence="@any" status="NS"
        tournament_id="1" type="RR" win_points="@any" />

    <player id="1" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="2" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="3" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="4" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="5" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />

    <groups id="1" name="@any" stage_id="1"/>
    
    <participant id="1" player_id="1" tournament_id="1" />
    <participant id="2" player_id="2" tournament_id="1" />
    <participant id="3" player_id="3" tournament_id="1" />
    <participant id="4" player_id="4" tournament_id="1" />
    <participant id="@any" player_id="5" tournament_id="1" /> 

</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/playOffGame/createPlayOffGameTest-verify.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../dataset.xsd">

    <tournament id="1" name="@any" status="RO" playing_format_id="@null" country="@any" city="@any" address="@any"
        logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp" visible="true" />

    <stage copy_result_stage_id="@null" id="1" name="@any" number_of_hockey="@any" sequence="@any" status="NS"
        tournament_id="1" type="RR" win_points="@any" />

    <player id="1" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="2" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="3" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="4" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />
    <player id="5" city="@any" club="@any" country="@any" date_of_birth="@date" gender="M" name_ascii="@any"
        name="@any" nickname="@any" surname_ascii="@any" surname="@any" verification="@any" world_ranking="@any" />

    <groups id="1" name="@any" stage_id="1" />

    <participant id="1" player_id="1" tournament_id="1" />
    <participant id="2" player_id="2" tournament_id="1" />
    <participant id="3" player_id="3" tournament_id="1" />
    <participant id="4" player_id="4" tournament_id="1" />
    <participant id="5" player_id="5" tournament_id="1" />

    <group_participant id="1" group_id="1" participant_id="1" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />
    <group_participant id="2" group_id="1" participant_id="2" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />
    <group_participant id="3" group_id="1" participant_id="3" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />
    <group_participant id="4" group_id="1" participant_id="4" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />
    <group_participant id="5" group_id="1" participant_id="5" points="@any" rank="@null" score="@any"
        secondary_rank="@null" />

    <play_off_game id="1" home_participant_id="1" away_participant_id="2" position="1" result="1:0"
        stage_id="1" status="WIN" />
    <play_off_game id="@any" home_participant_id="2" away_participant_id="1" position="2" result="0:1"
        stage_id="1" status="LOSE" />


</dataset>

=== hudi1/tomass/tablehockey/tahom-processor/src/test/java/it/participant/group/GroupParticipantIT.xml
<?xml version='1.0' encoding='UTF-8'?>
<dataset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../dataset.xsd">

    <tournament id="1" name="@auto" status="RO" playing_format_id="@null" country="@auto" city="@auto"
        address="@auto" logo="@null" registration_from="@timestamp" tournament_date="@date" registration_to="@timestamp"
        visible="true" />

    <stage copy_result_stage_id="@null" id="1" name="@auto" number_of_hockey="@auto" sequence="@auto" status="NS"
        tournament_id="1" type="RR" win_points="@auto" />

    <groups id="1" name="@auto" stage_id="1" />

    <player id="1" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />
    <player id="2" city="@auto" club="@auto" country="@auto" date_of_birth="@date" gender="M" name_ascii="@auto"
        name="@auto" nickname="@auto" surname_ascii="@auto" surname="@auto" verification="1" world_ranking="@auto"
        ithf_id="@auto" />

    <participant id="1" player_id="1" tournament_id="1" />

    <group_participant id="1" points="@auto" rank="@auto" score="0:0" secondary_rank="@auto"
        participant_id="1" group_id="1" />

</dataset>
